services:
  db:
    image: postgres:15
    container_name: posgrados_db
    environment:
      POSTGRES_USER: posgrados_user
      POSTGRES_PASSWORD: posgrados_pass
      POSTGRES_DB: posgrados_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U posgrados_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
