"""Add proyecto_grado models: proyecto, propuesta, reportes, evaluaciones

Revision ID: 1bbfd08c9158
Revises: 6451be1a53af
Create Date: 2026-01-22 07:42:27.711358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbfd08c9158'
down_revision: Union[str, None] = '6451be1a53af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyecto_grado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_director', sa.Integer(), nullable=False),
    sa.Column('id_codirector', sa.Integer(), nullable=True),
    sa.Column('id_programa', sa.Integer(), nullable=False),
    sa.Column('id_grupo_inv', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('PROPUESTA', 'EN_DESARROLLO', 'EN_EVALUACION', 'APROBADO', 'SUSTENTADO', 'GRADUADO', name='estadoproyecto'), nullable=True),
    sa.Column('tipo_documento', sa.Enum('PLAN_INVESTIGACION', 'PROPUESTA_TESIS', 'MONOGRAFIA', 'TRABAJO_APLICACION', name='tipodocumento'), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_aprobacion_propuesta', sa.DateTime(), nullable=True),
    sa.Column('fecha_sustentacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_grado', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_codirector'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['id_director'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['id_grupo_inv'], ['grupo_investigacion.id'], ),
    sa.ForeignKeyConstraint(['id_programa'], ['programa_posgrado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyecto_grado_id'), 'proyecto_grado', ['id'], unique=False)
    op.create_table('evaluacion_jurado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('id_evaluador', sa.Integer(), nullable=True),
    sa.Column('nombre_evaluador', sa.String(length=255), nullable=False),
    sa.Column('email_evaluador', sa.String(length=255), nullable=True),
    sa.Column('institucion', sa.String(length=300), nullable=True),
    sa.Column('tipo_evaluacion', sa.String(length=50), nullable=True),
    sa.Column('concepto', sa.String(length=50), nullable=True),
    sa.Column('calificacion', sa.String(length=10), nullable=True),
    sa.Column('url_evaluacion', sa.String(length=500), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_evaluador'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyecto_grado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluacion_jurado_id'), 'evaluacion_jurado', ['id'], unique=False)
    op.create_table('propuesta_tesis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('url_documento', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'ENVIADO', 'RECIBIDO', 'EN_ESPERA_EVALUADORES', 'ASIGNADO_EVALUADORES', 'EN_EVALUACION', 'SOLICITUD_NUEVA_VERSION', 'APROBADO_CON_CAMBIOS', 'NO_APROBADO', 'APROBADO', name='estadopropuesta'), nullable=True),
    sa.Column('evaluadores', sa.Text(), nullable=True),
    sa.Column('fecha_radicado', sa.DateTime(), nullable=True),
    sa.Column('fecha_limite_evaluacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyecto_grado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_proyecto')
    )
    op.create_index(op.f('ix_propuesta_tesis_id'), 'propuesta_tesis', ['id'], unique=False)
    op.create_table('reporte_semestral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=10), nullable=False),
    sa.Column('numero_reporte', sa.Integer(), nullable=True),
    sa.Column('url_informe', sa.String(length=500), nullable=False),
    sa.Column('aval_director', sa.Integer(), nullable=True),
    sa.Column('fecha_aval', sa.DateTime(), nullable=True),
    sa.Column('observaciones_director', sa.Text(), nullable=True),
    sa.Column('fecha_carga', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyecto_grado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_semestral_id'), 'reporte_semestral', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reporte_semestral_id'), table_name='reporte_semestral')
    op.drop_table('reporte_semestral')
    op.drop_index(op.f('ix_propuesta_tesis_id'), table_name='propuesta_tesis')
    op.drop_table('propuesta_tesis')
    op.drop_index(op.f('ix_evaluacion_jurado_id'), table_name='evaluacion_jurado')
    op.drop_table('evaluacion_jurado')
    op.drop_index(op.f('ix_proyecto_grado_id'), table_name='proyecto_grado')
    op.drop_table('proyecto_grado')
    # ### end Alembic commands ###
