"""Initial schema: personas, programas, estudiantes, materias

Revision ID: 6451be1a53af
Revises: 
Create Date: 2026-01-21 15:56:49.792799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6451be1a53af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facultad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_facultad_id'), 'facultad', ['id'], unique=False)
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_institucional', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('documento_identidad', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('linkedin_id', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_identidad')
    )
    op.create_index(op.f('ix_persona_email_institucional'), 'persona', ['email_institucional'], unique=True)
    op.create_index(op.f('ix_persona_id'), 'persona', ['id'], unique=False)
    op.create_table('escuela',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('id_facultad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_facultad'], ['facultad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_escuela_id'), 'escuela', ['id'], unique=False)
    op.create_table('grupo_investigacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('codigo_minciencias', sa.String(length=50), nullable=True),
    sa.Column('id_escuela', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_escuela'], ['escuela.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_minciencias')
    )
    op.create_index(op.f('ix_grupo_investigacion_id'), 'grupo_investigacion', ['id'], unique=False)
    op.create_table('programa_posgrado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('codigo_snies', sa.String(length=20), nullable=True),
    sa.Column('nivel', sa.Enum('ESPECIALIZACION', 'MAESTRIA', 'DOCTORADO', name='nivelprograma'), nullable=False),
    sa.Column('id_escuela', sa.Integer(), nullable=False),
    sa.Column('creditos_totales', sa.Integer(), nullable=True),
    sa.Column('creditos_obligatorios', sa.Integer(), nullable=True),
    sa.Column('creditos_electivos', sa.Integer(), nullable=True),
    sa.Column('creditos_investigacion', sa.Integer(), nullable=True),
    sa.Column('duracion_semestres', sa.Integer(), nullable=True),
    sa.Column('requiere_tesis', sa.Integer(), nullable=True),
    sa.Column('requiere_idioma', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_escuela'], ['escuela.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_snies')
    )
    op.create_index(op.f('ix_programa_posgrado_id'), 'programa_posgrado', ['id'], unique=False)
    op.create_table('cohorte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_programa', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.String(length=10), nullable=True),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_programa'], ['programa_posgrado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohorte_id'), 'cohorte', ['id'], unique=False)
    op.create_table('materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('id_programa', sa.Integer(), nullable=False),
    sa.Column('es_obligatoria', sa.Integer(), nullable=True),
    sa.Column('semestre_sugerido', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('prerequisitos', sa.Text(), nullable=True),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_programa'], ['programa_posgrado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_materia_id'), 'materia', ['id'], unique=False)
    op.create_table('estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_programa', sa.Integer(), nullable=False),
    sa.Column('id_cohorte', sa.Integer(), nullable=False),
    sa.Column('codigo_estudiante', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.Enum('ASPIRANTE', 'ACTIVO', 'CONDICIONAL', 'RESERVA', 'GRADUADO', 'RETIRADO', 'CANCELADO', name='estadoestudiante'), nullable=True),
    sa.Column('semestre_actual', sa.Integer(), nullable=True),
    sa.Column('promedio_acumulado', sa.String(length=10), nullable=True),
    sa.Column('tiene_beca', sa.Integer(), nullable=True),
    sa.Column('tipo_beca', sa.String(length=100), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('fecha_max_graduacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_grado', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cohorte'], ['cohorte.id'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['id_programa'], ['programa_posgrado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_estudiante'),
    sa.UniqueConstraint('id_persona')
    )
    op.create_index(op.f('ix_estudiante_id'), 'estudiante', ['id'], unique=False)
    op.create_table('inscripcion_materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.Column('periodo_completo', sa.String(length=10), nullable=True),
    sa.Column('tipo_inscripcion', sa.Enum('PRIMERA_VEZ', 'REPITIENDO', 'VALIDACION', name='tipoinscripcion'), nullable=True),
    sa.Column('estado', sa.Enum('INSCRITO', 'APROBADO', 'REPROBADO', 'CANCELADO', name='estadoinscripcion'), nullable=True),
    sa.Column('nota_final', sa.String(length=10), nullable=True),
    sa.Column('nota_aprobacion', sa.String(length=10), nullable=True),
    sa.Column('fecha_inscripcion', sa.DateTime(), nullable=True),
    sa.Column('fecha_calificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['id_materia'], ['materia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inscripcion_materia_id'), 'inscripcion_materia', ['id'], unique=False)
    op.create_table('requisito_grado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('creditos_obligatorios_cumplidos', sa.Integer(), nullable=True),
    sa.Column('creditos_electivos_cumplidos', sa.Integer(), nullable=True),
    sa.Column('creditos_investigacion_cumplidos', sa.Integer(), nullable=True),
    sa.Column('idioma_aprobado', sa.Integer(), nullable=True),
    sa.Column('tipo_certificacion_idioma', sa.String(length=100), nullable=True),
    sa.Column('fecha_aprobacion_idioma', sa.DateTime(), nullable=True),
    sa.Column('propuesta_aprobada', sa.Integer(), nullable=True),
    sa.Column('tesis_aprobada', sa.Integer(), nullable=True),
    sa.Column('fecha_sustentacion', sa.DateTime(), nullable=True),
    sa.Column('publicacion_requerida', sa.Integer(), nullable=True),
    sa.Column('tiene_publicacion', sa.Integer(), nullable=True),
    sa.Column('url_publicacion', sa.String(length=500), nullable=True),
    sa.Column('cumple_todos_requisitos', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisito_grado_id'), 'requisito_grado', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requisito_grado_id'), table_name='requisito_grado')
    op.drop_table('requisito_grado')
    op.drop_index(op.f('ix_inscripcion_materia_id'), table_name='inscripcion_materia')
    op.drop_table('inscripcion_materia')
    op.drop_index(op.f('ix_estudiante_id'), table_name='estudiante')
    op.drop_table('estudiante')
    op.drop_index(op.f('ix_materia_id'), table_name='materia')
    op.drop_table('materia')
    op.drop_index(op.f('ix_cohorte_id'), table_name='cohorte')
    op.drop_table('cohorte')
    op.drop_index(op.f('ix_programa_posgrado_id'), table_name='programa_posgrado')
    op.drop_table('programa_posgrado')
    op.drop_index(op.f('ix_grupo_investigacion_id'), table_name='grupo_investigacion')
    op.drop_table('grupo_investigacion')
    op.drop_index(op.f('ix_escuela_id'), table_name='escuela')
    op.drop_table('escuela')
    op.drop_index(op.f('ix_persona_id'), table_name='persona')
    op.drop_index(op.f('ix_persona_email_institucional'), table_name='persona')
    op.drop_table('persona')
    op.drop_index(op.f('ix_facultad_id'), table_name='facultad')
    op.drop_table('facultad')
    # ### end Alembic commands ###
