"""Add roles and vinculaciones with business rules

Revision ID: 682a51a5921e
Revises: 1bbfd08c9158
Create Date: 2026-01-22 18:01:41.302768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682a51a5921e'
down_revision: Union[str, None] = '1bbfd08c9158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('permisos', sa.Text(), nullable=True),
    sa.Column('nivel_minimo', sa.String(length=50), nullable=True),
    sa.Column('requiere_titulo', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_catalogo_rol_id'), 'catalogo_rol', ['id'], unique=False)
    op.create_table('vinculacion_activa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('tipo_contexto', sa.String(length=50), nullable=False),
    sa.Column('id_contexto', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('es_activo', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('asignado_por', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['catalogo_rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vinculacion_activa_id'), 'vinculacion_activa', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vinculacion_activa_id'), table_name='vinculacion_activa')
    op.drop_table('vinculacion_activa')
    op.drop_index(op.f('ix_catalogo_rol_id'), table_name='catalogo_rol')
    op.drop_table('catalogo_rol')
    # ### end Alembic commands ###
