"""Add solicitudes system with workflow and calendar

Revision ID: 8be791879e1f
Revises: fca39a85fde3
Create Date: 2026-01-22 18:15:17.397573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be791879e1f'
down_revision: Union[str, None] = 'fca39a85fde3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendario_solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.Column('periodo_completo', sa.String(length=10), nullable=True),
    sa.Column('tipo_solicitud', sa.Enum('CREDITO_CONDONABLE', 'PRORROGA', 'CAMBIO_DIRECTOR', 'CAMBIO_TITULO', 'REINGRESO', 'RETIRO_MATERIA', 'VALIDACION_MATERIA', 'HOMOLOGACION', 'CANCELACION_SEMESTRE', 'RESERVA_CUPO', 'MODIFICACION_DATOS', 'NOMBRAMIENTO_JURADO', 'SOLICITUD_GRADO', 'AUTORIZACION_SUSTENTACION', 'OTRA', name='tiposolicitud'), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=False),
    sa.Column('fecha_publicacion_resultados', sa.DateTime(), nullable=True),
    sa.Column('fecha_reporte_direccion', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendario_solicitud_id'), 'calendario_solicitud', ['id'], unique=False)
    op.create_table('solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_radicado', sa.String(length=50), nullable=True),
    sa.Column('tipo_solicitud', sa.Enum('CREDITO_CONDONABLE', 'PRORROGA', 'CAMBIO_DIRECTOR', 'CAMBIO_TITULO', 'REINGRESO', 'RETIRO_MATERIA', 'VALIDACION_MATERIA', 'HOMOLOGACION', 'CANCELACION_SEMESTRE', 'RESERVA_CUPO', 'MODIFICACION_DATOS', 'NOMBRAMIENTO_JURADO', 'SOLICITUD_GRADO', 'AUTORIZACION_SUSTENTACION', 'OTRA', name='tiposolicitud'), nullable=False),
    sa.Column('categoria', sa.Enum('ACADEMICA', 'ADMINISTRATIVA', 'INVESTIGACION', 'FINANCIERA', name='categoriassolicitud'), nullable=False),
    sa.Column('id_solicitante', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_proyecto', sa.Integer(), nullable=True),
    sa.Column('id_programa', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('documentos_adjuntos', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'ENVIADA', 'EN_REVISION', 'EN_COMITE', 'APROBADA', 'RECHAZADA', 'DEVUELTA', 'CANCELADA', name='estadosolicitud'), nullable=True),
    sa.Column('nivel_aprobacion_requerido', sa.Enum('DIRECTOR', 'COORDINADOR', 'COMITE', 'CONSEJO', name='nivelaprobacion'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('fecha_limite_respuesta', sa.DateTime(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_rechazo', sa.DateTime(), nullable=True),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.Column('id_quien_responde', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['id_programa'], ['programa_posgrado.id'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyecto_grado.id'], ),
    sa.ForeignKeyConstraint(['id_quien_responde'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['id_solicitante'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_radicado')
    )
    op.create_index(op.f('ix_solicitud_id'), 'solicitud', ['id'], unique=False)
    op.create_table('credito_condonable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.Column('periodo_completo', sa.String(length=10), nullable=True),
    sa.Column('modalidad', sa.String(length=100), nullable=True),
    sa.Column('materia_asignada', sa.String(length=300), nullable=True),
    sa.Column('horas_semanales', sa.Integer(), nullable=True),
    sa.Column('fecha_vinculacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_liquidacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('url_carta_director', sa.String(length=500), nullable=True),
    sa.Column('url_certificado_notas', sa.String(length=500), nullable=True),
    sa.Column('url_paz_salvo', sa.String(length=500), nullable=True),
    sa.Column('aprobado_comite', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion_comite', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_solicitud')
    )
    op.create_index(op.f('ix_credito_condonable_id'), 'credito_condonable', ['id'], unique=False)
    op.create_table('flujo_aprobacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Enum('DIRECTOR', 'COORDINADOR', 'COMITE', 'CONSEJO', name='nivelaprobacion'), nullable=False),
    sa.Column('id_responsable', sa.Integer(), nullable=True),
    sa.Column('rol_responsable', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_responsable'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flujo_aprobacion_id'), 'flujo_aprobacion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flujo_aprobacion_id'), table_name='flujo_aprobacion')
    op.drop_table('flujo_aprobacion')
    op.drop_index(op.f('ix_credito_condonable_id'), table_name='credito_condonable')
    op.drop_table('credito_condonable')
    op.drop_index(op.f('ix_solicitud_id'), table_name='solicitud')
    op.drop_table('solicitud')
    op.drop_index(op.f('ix_calendario_solicitud_id'), table_name='calendario_solicitud')
    op.drop_table('calendario_solicitud')
    # ### end Alembic commands ###
