"""Add roles and vinculaciones with business rules

Revision ID: fca39a85fde3
Revises: 682a51a5921e
Create Date: 2026-01-22 18:05:52.251914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca39a85fde3'
down_revision: Union[str, None] = '682a51a5921e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
